name: Build Examples Website
on: [push]
jobs:
  build-demo:
    name: Build Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # let pnpm version be determined from pkg.json
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: pnpm
      - name: Setup App
        run: sh setup.sh
      - name: Build Next App
        run: pnpm demo:build
