name: Build Examples Website
on: [push]
jobs:
  build-demo:
    name: Build Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      # let pnpm version be determined from pkg.json
      - name: Configure pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Configure Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Components Package
        run: pnpm -F @nish1896/rhf-mui-components run lib:build
      - name: Build Examples Website
        run: pnpm -F @nish1896/rhf-mui-demo run build
