name: Build Docs Website v3
on: [push]
jobs:
  build-docs:
    name: Build Docs v3
    runs-on: ubuntu-latest
    env:
      GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Configure Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: yarn
      - name: Install Yarn
        run: npm install -g yarn@1.22.22
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: yarn lib
      - name: Link built package
        run: |
          cd packages/rhf-mui-components/dist
          yarn link
          cd ../../../apps/rhf-mui-docs
          yarn link @nish1896/rhf-mui-components
      - name: Build Docs
        run: yarn docs:build
