name: Build Examples Website v3
on: [push]
jobs:
  build-demo:
    name: Build Examples v3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Setup App
        run: sh scripts/setup.sh
      - name: Build Next App
        run: yarn demo:build