name: Publish package on npm

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node env
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Build package
        run: yarn lib
      - name: Publish package on npm
        run: npm publish --tag latest
        working-directory: packages/rhf-mui-components/dist