name: Publish package on npm

on:
  push:
    tags:
      - 'v3.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node env
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup App and Build Package
        run: sh scripts/setup.sh
      # Running the below command would ensure that latest
      # "v3.x" of this package would only be installed
      #
      # npm install @nish1896/rhf-mui-components@v3
      - name: Publish package on npm
        run: npm publish --tag latest-v3
        working-directory: packages/rhf-mui-components/dist