name: Publish package on npm

on:
  push:
    tags:
      - 'v4.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish package on npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Setup Node env
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: pnpm
      - name: Setup App and Build Package
        run: sh scripts/setup.sh
      - name: Publish package on npm
        run: npm publish --tag latest
        working-directory: packages/rhf-mui-components/dist