name: Publish Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      
      - name: release @nish1896/rhf-mui-components
        run: yarn pkg:publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
